version: '3.8'

services:
  vueapp_test_e2e:
    networks:
      - fullstack # internally connects to backend for e2e tests
    build:
      context: .
      dockerfile: ./cypress.Dockerfile
    environment:
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
      - CYPRESS_TAGS=${CYPRESS_TAGS}
      # - CYPRESS_VERIFY_TIMEOUT=100000
      - CYPRESS_ENV_FILE=${CYPRESS_ENV_FILE}
    depends_on:
      vueapp_serve:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
