version: '3.8'

services:
  vueapp_serve_static:
    build:
      context: .
      target: serve-static-stage
      args:
        VUE_MODE: ${VUE_MODE}
    ports:
      - 8010:80
    networks:
      - traefik-public
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      # - "traefik.http.routers.frontend.tls.certresolver=le"
    # depends_on:
    #   fastapi:
    #     condition: service_healthy
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8080
    #   timeout: 2s
    #   retries: 10