version: '3.8'

services:
  vueapp_serve:
    profiles:
      - fullstack
      - frontend-dev
    build:
      context: .
      target: serve-local-stage
    volumes:
      - ./src:/app/src # live reload
    ports:
      - 8019:8080

  vueapp_serve_prod:
    profiles:
      - frontend-prod
    build:
      context: .
      target: serve-prod-stage
    ports:
      - 8010:80

  vueapp_test_e2e:
    profiles:
      - fullstack-e2e
    networks:
      - fullstack # internally connects to backend for e2e tests
    build:
      context: .
      dockerfile: ./cypress.Dockerfile
    environment:
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
    depends_on:
      - fastapi
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./cypress.json:/app/cypress.json
