version: '3.8'

services:
  vueapp_serve:
    build:
      context: .
      target: serve-local-stage
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    ports:
      - 8019:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my-app.rule=Host(`frontend.${PRIMARY_DOMAIN}`)"
      - "traefik.http.routers.my-app.entrypoints=websecure"
      - "traefik.http.routers.my-app.tls=true"
      - "traefik.http.routers.my-app.tls.certresolver=le"
    # depends_on:
    #   fastapi:
    #     condition: service_healthy
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8080
    #   timeout: 2s
    #   retries: 10
  # vueapp_serve_prod:
  #   profiles:
  #     - frontend-prod
  #   build:
  #     context: .
  #     target: serve-prod-stage
  #   ports:
  #     - 8010:80
