version: '3.8'

services:
  vueapp_test_e2e:
    networks:
      - fullstack
    build:
      context: .
      dockerfile: ./cypress.Dockerfile
    environment:
      - CYPRESS_VIDEO=${CYPRESS_VIDEO-true}
      - CYPRESS_TAGS=${CYPRESS_TAGS}
      # - CYPRESS_VERIFY_TIMEOUT=100000
      - CYPRESS_ENV_FILE=${CYPRESS_ENV_FILE}
      - CYPRESS_MAILSLURP_API_KEY=${CYPRESS_MAILSLURP_API_KEY}
    depends_on:
      fastapi:
        condition: service_healthy
    #   vueapp_serve:
    #     condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
