version: '3.8'

services:
  vueapp_serve_local:
    profiles:
      - fullstack-serve
    networks:
      - fullstack
    build:
      context: .
      target: serve-local-stage
    volumes:
      - ./src:/app/src # live reload
    ports:
      - 8019:8080

  vueapp_serve_dev:
    profiles:
      - frontend-dev-serve
    networks:
      - fullstack
    build:
      context: .
      target: serve-dev-stage
    volumes:
      - ./src:/app/src # live reload
    ports:
      - 8019:8080
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  vueapp_serve_prod:
    profiles:
      - frontend-prod-serve
    networks:
      - fullstack
    build:
      context: .
      target: serve-prod-stage
    ports:
      - 8010:80

  # vueapp_test_e2e_external:
  #   profiles:
  #     - fullstack-e2e-test-deployed
  #    context: .
  #    dockerfile: ./cypress.Dockerfile
  #    target: test-e2e-external
  #   volumes:
  #     - ./src:/app/src # live reload
  #     - ./tests:/app/tests # live reload

  fastapi_serve:
    profiles:
      - backend-serve
      - fullstack-serve
      - fullstack-e2e-test
    networks:
      - fullstack
      - backend
    build:
      context: ./backend/src/
      target: serve-stage
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - 8018:8018
    volumes:
      - ./backend/src:/app
    secrets:
      - mysql-password
    tty: true # enables colored log
    stdin_open: false # enables colored log 

  mysqldb:
    profiles:
      - backend-serve
      - fullstack-serve
      - fullstack-e2e-test
    networks:
      - backend
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  fullstack:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: backend/db/mysql_pwd.txt