version: '3.8'

services:
  vueapp_test_unit:
    profiles:
      - unit-test
    build:
      context: .
      target: test-unit-stage
    volumes:
      - ./src:/app/src # live reload
      - ./tests:/app/tests # live reload
    tty: true # enables colored log
    stdin_open: false # enables colored log

  vueapp_test_e2e:
    profiles:
      - fullstack-e2e-test
    networks:
      - fullstack
    depends_on:
      - fastapi_serve
    build:
      context: .
      dockerfile: ./cypress.Dockerfile
      target: test-e2e-stage
    environment:
      - VUE_APP_BACKEND_URL=http://fastapi_serve:8018
    volumes:
      - ./src:/app/src # live reload
      - ./tests:/app/tests # live reload

  fastapi_serve:
    profiles:
      - fullstack-e2e-test
    networks:
      - fullstack
      - backend
    build:
      context: ./backend/src/
      target: serve-stage
    restart: always
    environment:
      - ENV_FILE=.test.env
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - ./backend/src:/app
    secrets:
      - mysql-password
    tty: true # enables colored log
    stdin_open: false # enables colored log 

  mysqldb:
    profiles:
      - fullstack-e2e-test
    networks:
      - backend
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=login
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-password
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - mysql-password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  fullstack:
  backend:

volumes:
  mysql-data:

secrets:
  mysql-password:
    file: backend/db/mysql_pwd.txt